# permissions for end users to view runtimeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimeconfig-viewer-role
rules:
- apiGroups:
  - runtimeconfig.runtimeconfiguration.openshift.io
  resources:
  - runtimeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtimeconfig.runtimeconfiguration.openshift.io
  resources:
  - runtimeconfigs/status
  verbs:
  - get
